version: '3'

services:
  etcd-manage:
    image: "shiguanghuxian/etcd-manage"
    volumes:
      - ./bin/config/cfg.toml:/app/config/cfg.toml
      - ./bin/logs:/app/logs
    ports:
      - "10280:10280"
