# debug模式
debug = false
# 日志文件路径
log_path = ""

# http 监听端口
[http]
# 监听地址
address = "0.0.0.0"
# 监听端口
port = 10280

# 使用 Let's Encrypt 证书 - tls_enable为true优先使用本地证书模式
tls_encrypt_enable = false
# 域名列表
tls_encrypt_domain_names = ["shiguanghuxian.com"]

# 是否启用tls
tls_enable = false
# tls证书文件
[http.tls_config]
cert_file = "cert_file"
key_file = "key_file"


## mysql 配置
[db]
## 是否调试模式
debug = true
## 数据库连接地址
address = "127.0.0.1"
## 数据库端口
port = 3306
## 连接池最大连接数
max_idle_conns = 64
## 默认打开连接数
max_open_conns = 24
## 数据库用户名
user = "root"
## 数据库密码
passwd = "123456"
## 数据库名
db_name = "etcd-manage"
